% Purpose: special-measure function that facilitates the execution of
% Python code in Matlab, wrapping output into structures consistent with
% that of smrun, and bookkeeping for metadata (like channel values).
% 
% The Python code is run in a specific conda environment specified as a
% comment in the Python file in the form "# env :: <[some_environment].yml>",
% where [some_environment].yml lives in [parent directory]/environments/.
% smrunpyfile will do some basic checks to make sure that this environment
% exists and has already been created; if not, navigate to
% [parent directory]/environments/ in Matlab, and run the command
% system("conda env create -f [some_environment].yml"). The environment
% itself requires at least the smpy Python package, used inside the target
% Python file. In particular, the smpy.core functions are used to send
% important info from Python back to smrunpyfile through an IO stream,
% which is then parsed and saved in a manner similarly to how smrun would
% save it. As all of the raw data, code snapshots, and environment snapshots
% live in a folder generated by Python, smrunpyfile must receive the
% 'snapshot' location by Python or else it'll give an error; in order to
% enforce this, smrunpyfile does a simple check in the Python file for a
% call to the Python-to-Matlab communication function, and gives an error
% if it doesn't find it. *It is on the user to make sure data/metadata is
% appropriately snapshotted in the Python file*.
%
% Neither smrunpyfile nor its helper functions, nor smpy are implicitly capable of
% doing anything dangerous; i.e., they don't interface with nor reference
% instruments/channels in any capacity beyond bookkeeping. As such, implementing experimental
% guardrails is left up to the user as is the case with regular smrun usage.
%
% Please see smrunpyfile_example.py for a template of how a Python file is
% fed to smrunpyfile, including required snippets and further
% documentation on the Python side of things.
%
% Dependencies: conda, smpy, special-measure
% Authors: Malick Gaye, 8/26/26.
% Version: alpha
% No generative AI was used in development of this code.
% ---------------------------
% INPUTS:
% config is a struct with required fields:
%     parentdir: string (directory), containing the Python input file
%     *somewhere* in the subfolders. Additionally, parentdir must contain
%     an environments folder populated w/ the .yml file specified in the
%     Python file (e.g., parentdir/environments/some_environment.yml).
%     Matlab's working directory must also be in parentdir.
%     
%     input: string (.py file), pointing to the Python file in the working
%     directory that we want to execute. This is a *relative* path, defined
%     relative to the working directory for quality-of-life. Please see
%     smrunpyfile_example.py from smpy/examples to understand what this
%     Python file needs to work with smrunpyfile.
%
%     configch, cleanupfn: same as smrun
% filename is a string telling us where to save data. Exact same
%     functionality as smrun.
% ---------------------------
% OUTPUTS:
% (with function call data = smrunpyfile(config, filename)
% d = load(filename) is a struct with fields:
%     config: same struct as config above
%     stdout: standard output stream from Python (i.e., terminal output)
%     env: snapshot of conda environment that the Python was run in.
%       Can either be a struct or string dump. Also saved to QM snapshot.
%     snapshot: string pointing to folder containing all relevant
%       non-stream Python input and output; contains raw data, Python file
%       snapshots, JSON files, etc.
%     data: cell array similarly to what smrun would give. Only populated
%       by numpy data in the snapshot's .npz file generated by Python.
%     pyloops: similar to smrun's d.scan.loops struct. Only populated if
%       user specified loops([loopidx]).[field] keys in dict exported to
%       [JSON file] by Python. Please see smrunpyfile_example.py for more
%       information. This is not as straightforward as smrun's d.scan.loops
%       since one does not generally implement 'loop-like' programs on
%       platforms like Quantum Machines.
%     configvals: same as smrun output
%     configch: same as smrun output
%     configdata: same as smrun output
%     smdata_novisa: same as smrun output
% data is a numeric cell array (same as d.data above). This is returned to
%     maintain operational consistency with smrun.
% ---------------------------
% EXAMPLE:
% (with Matlab working directory [something]/Nichol Group/Data/2026_5_25_B01_D4/data 
%  and a Python file at [something]/Nichol Group/Data/2026_5_25_B01_D4/scripts/some_python_file.py)
%     config = struct();
%     config.parentdir = "[something]/Nichol Group/Data/2026_5_25_B01_D4";
%     config.input = "scripts/some_python_file.py";
%     filename = "sm_Ramsey_experiment.mat";
%     data = smrunpyfile(config, filename);
%     ^ (data is a numeric cell array, and we saved an smrun-like struct to
%        [something]/Nichol Group/Data/2026_5_25_B01_D4/data/sm_Ramsey_experiment.mat)
function data = smrunpyfile(config, filename)
    %% Initialize saved fields + basic checks
    % config:
    % Req. fields: input, parentdir
    % Optional fields: consts, configfn, cleanupfn

    debug = false;

    snapshot = ""; % Points to snapshot of Python files, data, env.
    data = {}; % Numeric data only, a la smget
    pyloops = struct();
    env = struct();
    stdout = "";

    global smdata;

    % Deleted dependence on smscan; unclear/potentially harmful behavior
    if nargin < 2
        error('smrunpyfile:validate_args', "config and filename must be provided to smrunpyfile.")
    end
    %% Validate config.parentdir first
    if ~isfield(config, 'parentdir') || isempty(config.parentdir)
        error('smrunpyfile:validate_path', "config.parentdir must be properly specified (e.g., 'Nichol Group/.../2025_5_25_B01_D4/')");
    end

    path_contains_fwd_and_bwd_slashes = @(s) (sum(char(s) == '/') > 0) && (sum(char(s) == '\') > 0);

    if path_contains_fwd_and_bwd_slashes(config.parentdir)
        error('smrunpyfile:validate_path', "parentdir string cannot simultaneously contain forward & backward slashes.")
    end
    %% Define configvals, configch
    % Copied from smrun for operational consistency
    if ~debug
        if isfield(config,'configch')
          configvals = cell2mat(smget(config.configch));    
        else
          configvals = cell2mat(smget(smdata.configch));
        end
    else
        if isfield(config,'configch')
          configvals = smdata.chanvals(config.configch);    
        else
          configvals = smdata.chanvals(smdata.configch);
        end
    end
    configch = {smdata.channels(smchanlookup(smdata.configch)).name};
    
    configdata = cell(1, length(smdata.configfn));
    for i = 1:length(smdata.configfn)
        if iscell(smdata.configfn)
            configdata{i} = smdata.configfn{i}();
        else
            configdata{i} = smdata.configfn(i).fn(smdata.configfn(i).args);   
        end
    end
    % End copy
    %% Figure out where we are in the parent directory
    
    % Remove anything that might come before "Nichol Group"
    parentdir = normalize_filepath(config.parentdir);
    parentdir = string(['Nichol Group' char(extractAfter(parentdir, "Nichol Group"))]);

    % We don't want to change the working directory. So we should find
    % where the python file is w.r.t. the working directory

    workingdir = normalize_filepath(pwd); % full path
    %workingdir = char(extractAfter(workingdir, parentdir));

    if ~contains(workingdir, parentdir)
        error('smrunpyfile:validate_path', "working directory must be somewhere in the parent directory. Please 'cd' accordingly.");
    end

    if ~contains(workingdir, parentdir)
        error('smrunpyfile:validate_path', "working directory must be in the parent directory. Please 'cd' accordingly.");
    end
    
    if path_contains_fwd_and_bwd_slashes(workingdir)
        error('smrunpyfile:validate_path', "Working directory can't simultaneously contain forward & backward slashes. Please 'cd' elsewhere.")
    end

    workingdir = split(workingdir,parentdir);
    workingdir = char(workingdir(end)); % everything after parentdir
    
    % Figure out how deep the working directory is in the parent directory
    is_slash = @(ch) (ch == '/') | (ch == '\');
    if isempty(workingdir)
        workingdirdepth = 0;
    elseif is_slash(workingdir(1))
        workingdirdepth = sum(is_slash(workingdir));
    else
        workingdirdepth = sum(is_slash(workingdir)) + 1;
    end

    %% Relativize paths
    % Assume 's' uses parentdir as working directory. Returns char
    % E.g., turns s = "a/b/c" to './../a/b/c' if working dir is
    % parentdir/d
    function c = relpath(s)
        c = normalize_filepath(s);
        path_cell = [{'.'}, repmat({'..'},1,workingdirdepth), {char(c)}];
        c = fullfile(path_cell{:});
    end
    %% Validate Python file and environment
    % Get Python file path relative to working directory
    pyfilepath = relpath(config.input);

    % Validate Python file exists
    envfilename = validate_python_file(config, pyfilepath);

    % Validate environment exists and has no conflicts
    envfilename = char(envfilename);
    envfilepath = relpath(char("environments/" + string(envfilename)));
    envname = validate_environment(config, envfilepath);

    %% Validate output filename
    % Copied from smrun for operational consistency
    if isempty(filename)
        filename = 'data';
    end
    
    if all(char(filename) ~= '/') && all(char(filename) ~= '\')
        filename = sprintf('sm_%s.mat', filename);
    end
    smavalidateFilename(filename);
    str = '';
    while (isfile(filename) || isfile([filename, '.mat'])) && ~strcmp(str, 'yes') 
        fprintf('File %s exists. Overwrite? (yes/no)', filename);
        while 1
            str = input('', 's');
            switch str
                case 'yes'
                    break;
                case 'no'
                    filename = sprintf('sm_%s.mat', input('Enter new name:', 's'));
                    break
            end
        end
    end

    if isfield(config,'consts') && ~isempty(config.consts)
        if ~isfield(config.consts,'set')
            for i=1:length(config.consts)
                config.consts(i).set =1;
            end
        end
        setchans = {};
        setvals = [];
        for i=1:length(config.consts)
            if config.consts(i).set
                setchans{end+1}=config.consts(i).setchan;
                setvals(end+1)=config.consts(i).val;
            end
        end
        smset(setchans, setvals);
    end

    if isfield(config, 'configfn')
        for i = 1:length(config.configfn)
            config = config.configfn(i).fn(config, config.configfn(i).args{:});
        end    
    end
    % End copy

    % config.disp is not relevant here. This must be handled by Python.
    % TODO: in the future, we can maybe incorporate this.
    %% Make initial save to Matlab output file
    % Copied from smrun for operational consistency
    smdata_novisa = smdata;
    for iInst=1:length(smdata_novisa.inst)
        try
            isvalid(smdata_novisa.inst(iInst).data.inst); %throws an error if the argument is not a visa object
            p = properties(smdata_novisa.inst(iInst).data.inst);
            for ip = 1:length(p)
                str = sprintf('instProperties.%s = smdata_novisa.inst(%d).data.inst.%s;', ...
                    p{ip},iInst,p{ip});
                eval(str);
            end
            smdata_novisa.inst(iInst).data.inst = instProperties;
        catch
            1;
        end
    end
    % End copy

    % Make initial save
    save(filename, 'config', 'snapshot', 'configvals', 'configdata', 'configch','smdata_novisa', 'data', 'pyloops', 'stdout', 'env');

    % Copied from smrun for operational consistency
    str = [configch; num2cell(configvals)];
    logentry(filename);
    logadd(sprintf('%s=%.3g, ', str{:}));
    % End copy
    %% Snapshot environment
    % Save in struct if possible, otherwise save as environment dump
    % string. If both of these fail then give warning and proceed.
    try
        [~, envdump] = system("conda list -n " + envname + " --json 2>NUL");
        try
            % jsondecode dump to struct.
            env = jsondecode(envdump);
        catch
            % Could get dump but could not jsondecode to struct. In this
            % case, just save the dump. No warning necessary.
            env = envdump;
        end
    catch
        % Could not get environment dump. Send warning and proceed.
        env = struct();
        warning('smrunpyfile:environment', "Could not dump environment " + envname + ".");
    end
    %% Run Python file in the conda environment
    % Note that Python session inherits Matlab's working directory.
    [statuscode, stdout] = system("conda run -n " + envname + " python " + pyfilepath);
    if statuscode ~= 0
        warning('smrunpyfile:runtime', "%s may have exited with error (exit code = %d).", config.input, statuscode);
        save(filename, 'config', 'snapshot', 'configvals', 'configdata', 'configch','smdata_novisa', 'data', 'pyloops', 'stdout', 'env');
    end
    %% Print Python output to stream
    if isfield(config, 'print_stdout') && config.print_stdout
        % Print stdout to terminal
        fprintf("BEGIN PYTHON OUTPUT:\n");
        if endsWith(str, newline)
            fprintf(2,'%s',d.stdout);
        else
            fprintf(2,'%s\n',d.stdout);
        end
        fprintf("END PYTHON OUTPUT\n");
    end
    %% Read Python/Matlab IO stream
    % Currently just uses standard output stream (stdout) to receive info
    % from Python. If we want to change this in the future, pipe output to
    % relevant stream and then read from that file. Note that the argument
    % of the smpy function send_messages_to_matlab will need to change to
    % reflect the new output stream.
    outstream = stdout;
    %% Check stdout for snapshot location. Give warning if none found
    % 'snapshot' is sent in the IO stream by Python. If not found, then
    % throw error (not a warning, since this is rather critical).
    try
        snapshot = first_regex_match( ...
            outstream, ...
            format_IO_regex_expression('snapshot'), ...
            sprintf("Could not find snapshot location in %s output", config.input), ...
            'smrunpyfile:read_IO_stream' ...
        );
    catch exc
        warning('smrunpyfile:read_IO_stream', 'Could not locate snapshot; saving stdout and throwing error.');
        save(filename, 'config', 'snapshot', 'configvals', 'configdata', 'configch','smdata_novisa', 'data', 'pyloops', 'stdout', 'env');
        rethrow(exc);
    end
    %% Populate data field using snapshot location
    % data_file is the location of .mat file converted from .npz file
    % that's been sent by Python. We try to read data_file from the IO
    % stream and load the Matlab struct. If either of these fail, the
    % numeric data struct is empty, and it's on the user to retrieve and
    % parse the numeric data using the snapshot location. Send warning if
    % this happens.
    try
        data_file = first_regex_match( ...
            outstream, ...
            format_IO_regex_expression('data'), ...
            'smrunpyfile:read_IO_stream' ...
        );
        try
            datastruct = load(normalize_filepath(data_file));

            % Convert to cell array a la smget
            fields = fieldnames(datastruct);
            data = cell(1, numel(fields));
            
            for i = 1:numel(fields)
                data{i} = datastruct.(fields{i});
            end
        catch
            data = {};
            warning('smrunpyfile:data', "Could not load %s numeric data at %s. Note that numeric data filepath must be defined relative to Matlab working directory (pwd).", config.input, data_file);
        end
    catch
        data = {};
        warning('smrunpyfile:data', "Could not find numeric data location in %s output.", config.input)
    end
    %% If loops JSON contains scan-like info, populate pyloops field
    % In data JSON, look for fields of the name loops(loopidx).[fieldname]
    % or loops(loopidx).[fieldname](fieldidx). Use these to populate the
    % pyloops struct array.

    % Open data.json if exists.
    % Still relative to Matlab working directory.
    try
        json_file = first_regex_match( ...
            outstream, ...
            format_IO_regex_expression('loops'), ...
            'smrunpyfile:read_IO_stream' ...
        );
        try
            json_str = fileread(normalize_filepath(json_file));
            jsondata = jsondecode(json_str);

            % Was able to load JSON data.
            fields = fieldnames(jsondata);
            
            % Iterate through JSON fields and look for keys of the form
            % loops_[loopno]_[loopfield]. If found, populate
            % pyloops(loopno).(loopfield) w/ corresponding value in JSON.
            for i = 1:numel(fields)
                field = fields{i};

                % This will ONLY look for matches where the loop index and
                % and field name are specified. That is, 'loops_3' and
                % 'loops_setchan' will not match, as these are ambiguous
                % field names.
                matches = regexp(field, '\s*loops_+([0-9]+)_+([a-zA-Z]+)', 'tokens', 'once');
                
                if isempty(matches)
                    continue
                end

                % This necessarily matches with something, so no need to
                % check. Only difference is we've taken the loop index out
                % of the capture group.
                full_loopfield = regexp(field, '\s*loops_+[0-9]+_+([a-zA-Z_0-9]+)', 'tokens', 'once');
                full_loopfield = full_loopfield{1};

                loopno = str2double(matches{1}); % e.g., 2
                loopfield = matches{2}; % e.g., 'setchan'

                try
                    currval = pyloops(loopno).(loopfield);
                catch
                    currval = [];
                end

                try
                    [true_loopfield, newval] = map_to_pyloops(full_loopfield, currval, jsondata.(field));
                catch exc
                    if strcmp(exc.identifier, 'smrunpyfile:JSON')
                        % If an ambiguous field was found, just skip it and
                        % continue
                        warning(exc.identifier, '%s', exc.message);
                        continue;
                    else
                        % Some other error happend, rethrow error
                        rethrow(exc);
                    end
                end

                pyloops(loopno).(true_loopfield) = newval;

            end
        catch exc
            warning(['smrunpyfile:' char(exc.identifier)], "Could not load/process JSON file %s generated by Python scripts %s; pyloops struct not fully populated.", json_file, config.input);
        end
    catch
        warning('smrunpyfile:JSON', "Could not find JSON file generated by Python scripts %s.", config.input);
    end
    %% Run cleanup function if defined
    % Copied from smrun for operational consistency
    if isfield(config, 'cleanupfn')
        for k = 1:length(config.cleanupfn)
            config = config.cleanupfn(k).fn(config, config.cleanupfn(k).args{:});
        end
    end
    % End copy
    %% Save to output .mat file
    save(filename, 'config', 'snapshot', 'configvals', 'configdata', 'configch','smdata_novisa', 'data', 'pyloops', 'stdout', 'env');
end

function [true_loopfield, newval] = map_to_pyloops(loopfield, currval, jsonfieldval)
    function idx = extract_field_element_idx(stem)
        try
            idx = regexp(loopfield, [char(stem) '_+([0-9]+)'], 'tokens', 'once');
            idx = str2double(idx{1});
        catch
            % No index found
            idx = 1;
        end
    end

    % Functionality for callable types (e.g., prefn, postfn, trafofn) not
    % implemented.
    % fieldtypes{i, j} -> loops(idx).[field name] = [default type]
    % ... where i labels the field name and j labels the default type
    % (lists and cells only for now).
    fieldtypes_cell = {
        'rng', []; ...
        'npoints', []; ...
        'ramptime', []; ...
        'getchan', {}; ...
        'setchan', {}; ...
    };
    fieldtypes_not_implemented = {
        'prefn', ...
        'postfn', ...
        'procfn', ...
        'trafofn' ...
    };

    cellidx = find(cellfun(@(x) contains(loopfield, x), fieldtypes_cell(:,1)'));

    % There must be only one match. Anything else is ambiguous or an error.
    if numel(cellidx) ~= 1
        % If something like prefn or postfn fields were specified in the
        % JSON, we don't know how to implement this quite yet.
        unimplemented_fieldtype_match = find(cellfun(@(x) contains(loopfield, x), fieldtypes_not_implemented));
        if numel(unimplemented_fieldtype_match) > 0
            error('smrunpyfile:JSON', 'Processing for pyloops field %s is unimplemented. Not populating pyloops corresponding field.', fieldtypes_not_implemented{1});
        end

        % Otherwise, if we have multiple matches or no matches, this is an
        % error with the JSON. In the former case the pyloops field is
        % ambiguous, and in the latter case we don't know what the field is
        % supposed to look like (e.g., numeric or strings?)
        loopfield_prefix = split(loopfield, '_');
        loopfield_prefix = loopfield_prefix{1};
        error('smrunpyfile:JSON', 'JSON pyloops field name %s is ambiguous. Not populating pyloops corresponding field.', loopfield_prefix);
    end

    if ~(ischar(jsonfieldval) || isstring(jsonfieldval)) && numel(jsonfieldval) > 1
        % If jsonfieldval is array-like, ignore any indices found in
        % loopfield, and just set the entire value to jsonfieldval. In the
        % future, we may want to change this, but I can't think of a case
        % where you would want to.
        if numel(size(jsonfieldval)) == 2 && any(size(jsonfieldval) == 1)
            newval = jsonfieldval(:)'; % Flatten where reasonable
        else
            newval = jsonfieldval;
        end
    else
        validx = extract_field_element_idx(fieldtypes_cell{cellidx, 1});
        if isempty(currval)
            newval = fieldtypes_cell{cellidx, 2};
        else
            newval = currval;
        end
        try
            newval(validx) = jsonfieldval;
        catch
            newval(validx) = {jsonfieldval};
        end
    end

    true_loopfield = fieldtypes_cell{cellidx, 1};

end

function match = first_regex_match(input, expression, errormsg, erroridentifier)
    if nargin == 2
        errormsg = sprintf("Could not match expression '%s'", expression);
        erroridentifier = 'smrunpyfile:regex';
    elseif nargin == 3
        erroridentifier = 'smrunpyfile:regex';
    elseif nargin < 2
        error('smrunpyfile:first_regex_match', 'Not enough arguments.')
    end

    matches = regexp(input, expression, 'tokens', 'once');

    if isempty(matches)
        error(erroridentifier, errormsg);
    end

    match = matches{1};
end

% Matlab receives messages from Python via IO stream; the form of the
% message is currently [tag]::<[message]>, where [message] is captured by
% first_regex_match.
function expression = format_IO_regex_expression(tag, message_fmt)
    if nargin == 1
        % Default: message can be anything of any length except for the
        % message terminator '>'.
        message_fmt = '[^>]*';
    end

    expression = ['\s*' char(tag) '\s*::\s*<(' char(message_fmt) ')>'];
end

function envfilename = validate_python_file(config, relpath)
    % Check that Python file exists
    if ~isfile(relpath)
        error('smrunpyfile:validate_python_file', "Could not find Python file %s (rel. path: %s)", config.input, relpath);
    end
    
    % Read input Python file ( = config.input)
    pythoncode = fileread(relpath);

    % Python files run with smrunpyfile must communicate with Matlab in
    % order for the output .mat file to properly populate. Quickly check
    % that smpy_to_matlab.send_messages_to_matlab is called *somewhere* in
    % the Python file.
    if isempty(regexp(pythoncode, '[^a-zA-Z0-9_]*send_messages?_to_matlab\(', 'match'))
        error('smrunpyfile:validate_python_file', "smpy_to_matlab.send_messages_to_matlab must be called in file %s to send 'snapshot' (folder) path and 'data' (.npz file) path to Matlab.", config.input);
    end

    % Find the environment name in a comment
    % Match any Python comment of the form:
    % [whitespace(s)]#[whitespace(s)]env[whitespace(s)]::[whitespace(s)]<[something].yml>
    % ... and match{1} would then be "[something].yml"
    envfilename = first_regex_match( ...
        pythoncode, ...
        format_IO_regex_expression('#\s*env', '[^>]+\.yml'), ...
        sprintf("Could not find environment specification in %s (rel. path: %s). Please add comment to Python file of form '# env :: <[environment yml file name].yml>' (e.g., '# env :: <qmenv.yml>')", config.input, relpath), ...
        'smrunpyfile:validate_python_file' ...
    );
end

% Known possible bugs:
% jsondecode can fail if the preceding system command returns extra text
% that is not JSON text; e.g., FutureWarnings or something like that.
function envname = validate_environment(config, relpath)
    % Check that environment file exists
    if ~isfile(relpath)
        error('smrunpyfile:validate_environment', "Could not find environment %s from config %s", relpath, config.input);
    end

    % Check if environment exists
    [~, result] = system("conda env list --json 2>NUL");
    envs = jsondecode(result);
    envs_struct = envs.envs(:)';
    env_names = cell(1, size(envs_struct,2));
    for i = 1:size(envs_struct,2)
        env_names{i} = normalize_filepath(envs_struct{i});
    end

    % Find environment name from file
    envname = first_regex_match( ...
        fileread(relpath), ...
        'name:\s*(\S+)', ...
        sprintf("Could not find environment name in %s (config: %s)", relpath, config.input), ...
        'smrunpyfile:validate_environment' ...
    );

    % Check environment exists
    if ~any(contains(env_names, envname))
        error('smrunpyfile:validate_environment', "Environment " + relpath + " has not been created yet; please install relevant packages and create conda environment (conda env create -f <env. file>).")
    end
end

% Make file separators consistent, remove double file separators, remove
% trailing file seperators. If necessary in the future, perhaps append './'
% and remove leading file separators.
% Known bugs: if a filepath *actually* has/needs double-separators, this
% will explicitly break that.
function c = normalize_filepath(s)
    c = char(s);

    % Make file separators consistent and replace w/ filesep
    c = strrep(c, '\', '/');
    c = strrep(c, '/', filesep);

    % Remove trailing slash if present
    if c(end) == filesep
        c = c(1:(end-1));
    end

    % Fix double slashes (e.g., a/b//c -> a/b/c)
    c = strrep(c, [filesep filesep], filesep);
end
