%% Fit datasets individually.

files=get_files('sm_lineRF_A*');
files=fliplr(files);

% find the lever arm. Assume tunneling is zero, and assume electron
% temperature is the mc temp.
MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];

xvTot=[]; dataTot=[];
for i=1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    scantime=getscantime(scan,d.data);
    xv = plsinfo('xval',scan.data.pulsegroups.name,[],scantime);
    start=10;
    xv=xv(1,:);
    xv=xv(10:end);
    data=data(10:end);
    
    %MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    
    %beta(6)=sqrt((MCtemp(i)*1000)^2+50^2);
    %beta(6)=MCtemp(i)*1000;
    
    
    %p(1) offset
    mask(1)=1;
    beta(1)=data(1)+.005;
    %p(2) linear sensor response
    mask(2)=1;
    beta(2)=(data(50)-data(1))./(xv(50)-xv(1));
    %p(3) ampltiude
    mask(3)=1;
    beta(3)=-.0002;
    %p(4) center
    mask(4)=1;
    beta(4)=-.7;
    %p(5) lever arm
    mask(5)=0;
    beta(5)=.102;
    %p(6) electron temperature
    mask(6)=0;
    beta(6)=.06; %will be overwritten.
    %p(7) tunnel coupling in mV
    mask(7)=1;
    beta(7)=1.*.5*5.6e9/242e3*1e-6;
    %p(8) quadratic background
    mask(8)=1;
    beta(8)=0;
    %p(9) cubic background
    mask(9)=1;
    beta(9)=0;
    
    transfn2=@(p,x) charge_transition2(p,x);
    
    if 1
        beta = fitwrap('plfit plinit robust', xv, data, beta, transfn2, mask);
    else
        options=optimset('Display','off','MaxIter',1000);
        beta=lsqcurvefit(fitfn,beta,xv,data,lb,ub,options);
    end
    arm(i)=abs(beta(5));
    etemp(i)=abs(beta(6));
    center(i)=beta(4);
    
    xvTot(:,i)=(max(xv)-min(xv))*(i-1)+xv;
    dataTot(:,i)=data;
    
end

% figure(1); clf; plot(MCtemp,arm); xlabel('MC temp'); ylabel('Lever arm');
% figure(2); clf; plot(center);
% figure(3); clf; plot(MCtemp*1000,etemp,'bo'); hold on; plot(MCtemp*1000,MCtemp*1000,'r-');

% xlabel('MC temp'); ylabel('Electron temp');


%% Fit all data sets with the same lever arm and tunnel coupling. Allow electron temp to vary.
% Takes RF line scans generated by measure_electron_temp_2014_10_1, and
% fits them to extract the tunnel coupling, lever arm, and electron temp. 
files=get_files('sm_lineRF_A*');
files=fliplr(files);

% find the lever arm. Assume tunneling is zero, and assume electron
% temperature is the mc temp.
MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];data = [];

%     x is in mv
% 	  p(1) is tunnel coupling in mV
%     p(2) is lever arm
%     p(3) offset
%     p(4) linear sensor response
%     p(5) amplitude
%     p(6) center
%     p(7) electron temperature in mK
%     p(8) quadratic background
%     p(9) cubic background


fitfn = @(p,x) charge_transition3(p,x);
numVar=7;
width=1;

beta0=[.01 .14];
mask=[1 0];
mdata=struct(); model=struct();
for i = 1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    scantime=getscantime(scan,d.data);
    MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    xv = plsinfo('xval',scan.data.pulsegroups.name,[],scantime);
    xv=xv(1,:);
    
    %make an educated case where the center is
    [val ind]=max(abs(diff(data)));
    center=xv(ind);

    inds=xv>(center-width) & xv<(center+width);
    xv=xv(inds);
    data=data(inds);
    start=10; %exclude the first set of points
    
    xv=xv(start:end);
    data=data(start:end);

    offst=numVar*(i-1);
    mdata(i).y=data;
    mdata(i).x=xv;
    model(i).fn = fitfn;
    model(i).pt = @(p) [p(1) p(2) p(3+offst:9+offst)];
    mask = [mask 1 1 1 1 1 0 0];
    beta0=[beta0 data(1) (data(50)-data(1))./(xv(50)-xv(1)) -.0002 -.7 MCtemp(i)*1000 0 0];
end

beta = mfitwrap(mdata,model,beta0,'plinit plfit lm',mask);

%pull out the data
etemp=[]; etempGuess=[];
for i=1:length(files)
    offst=numVar*(i-1);
    etempGuess(i)=beta0(7+offst);
    etemp(i)=beta(7+offst);
end

figure(1); clf; plot(MCtemp*1000,etemp,'bo'); hold on; plot(MCtemp*1000,MCtemp*1000,'r-');
xlabel('MC temp (mK)'); ylabel('Electron temp (mK)');
title(sprintf('Tunnel coupling is %.0f ueV\nLever arm is %.2f',beta(1)*1000,beta(2)));


%% 2015/02/18: fit all line scans together: deprecated
files=get_files('sm_line_A*');
files=fliplr(files);

MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];data = [];

%     x is in mv
% 	  p(1) is tunnel coupling in mV
%     p(2) is lever arm
%     p(3) offset
%     p(4) linear sensor response
%     p(5) amplitude
%     p(6) center
%     p(7) electron temperature in mK
%     p(8) quadratic background
%     p(9) cubic background


fitfn = @(p,x) charge_transition3(p,x);
numVar=7;

beta0=[.01 .1];
mask=[1 1];
center=.6;
amp=.2e-3;
width=.7; %mV on either side of center to 

mdata=struct(); model=struct();
for i = 1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    try
        MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    catch 
        %get the temperature from the title.
        ind=regexp(files{i},'mK');
        temp=files{i}(ind-3:ind-1);
        temp(temp=='_')=[];
        MCtemp(i)=str2num(temp)*1e-3; 
    end
    %xv has units of mV.
    xv = linspace(d.scan.loops(1).rng(1),d.scan.loops(1).rng(2),d.scan.loops(1).npoints)*1e3;
    inds=xv>(center-width) & xv<(center+width);
    xv=xv(inds);
    data=data(inds);
    start=10; %exclude the first set of points
    xv=xv(1,:);
    xv=xv(10:end);
    data=data(10:end);
    offst=numVar*(i-1);
    mdata(i).y=data;
    mdata(i).x=xv;
    model(i).fn = fitfn;
    model(i).pt = @(p) [p(1) p(2) p(3+offst:9+offst)];
    mask = [mask 1 1 1 1 1 0 0];
    beta0=[beta0 data(1) (data(end)-data(1))./(xv(end)-xv(1)) amp center MCtemp(i)*1000 0 0];
end

beta = mfitwrap(mdata,model,beta0,'plinit plfit lm',mask);

%pull out the data
etemp=[]; etempGuess=[];
for i=1:length(files)
    offst=numVar*(i-1);
    etempGuess(i)=beta0(7+offst);
    etemp(i)=beta(7+offst);
end

figure(1); clf; plot(MCtemp*1000,etemp,'bo'); hold on; plot(MCtemp*1000,MCtemp*1000,'r-');
xlabel('MC temp (mK)'); ylabel('Electron temp (mK)');
title(sprintf('Tunnel coupling is %.0f ueV\nLever arm is %.2f',beta(1)*1000,beta(2)));

%% 2015/02/18: fit all lead scans together: deprecated
files=get_files('sm_lead_A*');
files=fliplr(files);


MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];data = [];

%     x is in mv
% 	  p(1) is tunnel coupling in mV
%     p(2) is lever arm
%     p(3) offset
%     p(4) linear sensor response
%     p(5) amplitude
%     p(6) center
%     p(7) electron temperature in mK
%     p(8) quadratic background
%     p(9) cubic background


fitfn = @(p,x) lead_transition(p,x);
numVar=7;

beta0=[.01 .13];
mask=[0 0];
center=-1.1;
amp=10e-3;
width=10; %mV on either side of center to 

mdata=struct(); model=struct();

%figure(5); clf; hold on;
for i = 1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    try
        MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    catch 
        %get the temperature from the title.
        ind=regexp(files{i},'mK');
        temp=files{i}(ind-3:ind-1);
        temp(temp=='_')=[];
        MCtemp(i)=str2num(temp)*1e-3; 
    end
    %xv has units of mV.
    xv = linspace(d.scan.loops(1).rng(1),d.scan.loops(1).rng(2),d.scan.loops(1).npoints)*1e3;
    inds=xv>(center-width) & xv<(center+width);
    xv=xv(inds);
    xv(2)-xv(1)
    data=data(inds);   
    slopeInd=10;
    slope=(data(slopeInd)-data(1))/(xv(slopeInd)-xv(1));
    %[val maxInd]=max(diff(data));
    %center=xv(maxInd);
    offst=numVar*(i-1);

    mdata(i).y=data;
    mdata(i).x=xv;
    model(i).fn = fitfn;
    model(i).pt = @(p) [p(1) p(2) p(3+offst:9+offst)];
    Ttherm=0; %assume thermalization above this temperature (mK)
    mask = [mask 1 1 1 1 (MCtemp(i)*1000)<Ttherm 0 0];  
    
    beta0=[beta0 (mean(data)-amp/2) slope amp center MCtemp(i)*1000 0 0];
end

beta = mfitwrap(mdata,model,beta0,'plinit plfit lm',mask);

%pull out the data
etemp=[]; etempGuess=[];
for i=1:length(files)
    offst=numVar*(i-1);
    etempGuess(i)=beta0(7+offst);
    etemp(i)=beta(7+offst);
end

figure(2); clf; plot(MCtemp*1000,etemp,'bo'); hold on; plot(MCtemp*1000,MCtemp*1000,'r-');
xlabel('MC temp (mK)'); ylabel('Electron temp (mK)');
title(sprintf('Tunnel coupling is %.0f ueV\nLever arm is %.2f',beta(1)*1000,beta(2)));

%% 2015/02/18: fit all lead scans separately to the fermi function and compare widths
%This appears to be the most trustworthy determination of electron temp.
files=get_files('sm_lead_A*');
files=fliplr(files);


MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];data = [];



beta0=[.029 .15];
mask=[1 1];
center=-0.2;
amp=10e-3;
width=1; %mV on either side of center to 

widthFit=[];
slopeFit=[];
centerFit=[];
offstFit=[];
ampFit=[];
unitlessTemp=[];
figure(5); clf; hold on;
for i = 1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    try
        MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    catch 
        %get the temperature from the title.
        ind=regexp(files{i},'mK');
        temp=files{i}(ind-3:ind-1);
        temp(temp=='_')=[];
        MCtemp(i)=str2num(temp)*1e-3; 
    end
    %xv has units of mV.
    xv = linspace(d.scan.loops(1).rng(1),d.scan.loops(1).rng(2),d.scan.loops(1).npoints)*1e3;

    
        %make an educated case where the center is
    [val ind]=max(diff(data));
    center=xv(ind);

    inds=xv>(center-width) & xv<(center+width);
    xv=xv(inds);
    data=data(inds);
    start=10; %exclude the first set of points
    xv=xv(1,:);
    xv=xv(10:end);
    data=data(10:end);
    %offst=numVar*(i-1);

    fitfn=@(p,x) p(1) +p(2).*x + p(3)./(exp(((x-p(4))./p(5)))+1);

    mask = [1 1 1 1 1]; %assume thermalization above 200 mK 
    beta0=[data(1) (data(2)-data(1))./(xv(2)-xv(1)) amp center .1];
    beta = fitwrap('plinit plfit',xv,data,beta0,fitfn, mask);
    fit=fitfn(beta,xv);
    figure(5);
    subplot(7,6,i); hold on; plot(xv,data,'k.'); plot(xv,fit,'b');
    title(sprintf('Width is %.0f ueV\nLever arm is %.2f',beta(5)*1000,beta(2)));
    widthFit(i)=abs(beta(5));

    figure(2); clf; plot(MCtemp*1000,widthFit*1e3,'bo'); 
    xlabel('MC temp (mK)'); ylabel('Lead width (uV)');
    ax=axis;
axis([0 ax(2) 0 ax(4)]);
end
%%
Ttherm=140; %assume electrons are thermalized above this temperature
inds=MCtemp.*1000>Ttherm;
fitfn=@(p,x) p(1).*x; %fit temperatures above this to a line going through zero
beta0=widthFit(4)/MCtemp(4);
beta=fitwrap('plinit plfit',MCtemp(inds),widthFit(inds),beta0,fitfn);
%figure(3); clf; plot(MCtemp*1000,unitlessTemp./beta(1),'bo'); 
figure(3); clf; plot(MCtemp*1000,widthFit*1e3./beta(1),'bo'); 

fit=fitfn(beta,MCtemp);
hold on; plot(MCtemp*1000,fit*1e3./beta(1),'r')
    ax=axis;
axis([0 ax(2) 0 ax(4)]);
xlabel('MC temp (mK)');
ylabel('Electron temmp(mK)');

%% The below files are a good set for electron thermometry, not tunnel broadened
files={ 'sm_lead_A_3632.mat'...
 'sm_lead_A_3631.mat'...
 'sm_lead_A_3630.mat'...
 'sm_lead_A_3629.mat'...
 'sm_lead_A_3628.mat'...
 'sm_lead_A_3627.mat'...
 'sm_lead_A_3626.mat'...
 'sm_lead_A_3625.mat'...
 'sm_lead_A_291mK_3623.mat'...
 'sm_lead_A_280mK_3621.mat'...
 'sm_lead_A_270mK_3619.mat'...
 'sm_lead_A_260mK_3617.mat'...
 'sm_lead_A_250mK_3615.mat'...
 'sm_lead_A_241mK_3613.mat'...
 'sm_lead_A_229mK_3611.mat'...
 'sm_lead_A_220mK_3609.mat'...
 'sm_lead_A_210mK_3607.mat'...
 'sm_lead_A_200mK_3605.mat'...
 'sm_lead_A_190mK_3603.mat'...
 'sm_lead_A_180mK_3601.mat'...
 'sm_lead_A_170mK_3599.mat'...
 'sm_lead_A_160mK_3597.mat'...
 'sm_lead_A_150mK_3595.mat'...
 'sm_lead_A_140mK_3592.mat'...
 'sm_lead_A_130mK_3589.mat'...
 'sm_lead_A_120mK_3586.mat'...
 'sm_lead_A_110mK_3583.mat'...
 'sm_lead_A_105mK_3580.mat'...
 'sm_lead_A_101mK_3577.mat'...
 'sm_lead_A_ 95mK_3574.mat'...
 'sm_lead_A_ 61mK_3571.mat'...
 'sm_lead_A_ 90mK_3568.mat'...
 'sm_lead_A_ 85mK_3565.mat'...
 'sm_lead_A_ 81mK_3562.mat'...
 'sm_lead_A_ 75mK_3559.mat'...
 'sm_lead_A_ 70mK_3556.mat'...
 'sm_lead_A_ 65mK_3553.mat'...
 'sm_lead_A_ 60mK_3550.mat'...
 };

%% Plot some echo data 
temp=[85 90 95 101 110 120 130 61 85 70 65 61 71 79];
T2=[552 472 536 515 502 606 488 541 552 611 646 619 571 553 ];
Q=[67 56 69 67 66 70 64 71 67 73 77 73 71 68];
figure(333); subplot(2,1,1); plot(temp,Q,'bo'); title('Q J = 120 MHz dJde= 160 MHz/mV '); xlabel('MC temp (mK)'); ylabel('Q')
subplot(2,1,2); plot(temp,T2,'bo'); title('T2. J = 120 MHz dJde = 160 MHz/mV'); xlabel('MC temp (mK)'); ylabel('T2')

%% 2015/02/26: analyze the pulse-based lead scan.
files=get_files('sm_lead_*');
files=fliplr(files);


MCtemp=[];
mask=[]; beta=[]; center=[]; etemp=[]; arm=[];data = [];



beta0=[.029 .15];
mask=[1 1];
%center=0.3;
amp=10e-3;
width=1; %mV on either side of center to 

widthFit=[]; widthErr=[];
slopeFit=[];
centerFit=[];
offstFit=[];
ampFit=[];
unitlessTemp=[];
figure(5); clf; hold on;
for i = 1:length(files)
    d=load(files{i});
    scan=d.scan;
    data=squeeze(nanmean(d.data{1}));
    try
        MCtemp(i)=d.configvals(strcmp(d.configch,'MC'));
    catch
        %get the temperature from the title.
        ind=regexp(files{i},'mK');
        temp=files{i}(ind-3:ind-1);
        temp(temp=='_')=[];
        MCtemp(i)=str2num(temp)*1e-3;
    end
    %xv has units of mV.
    
    scantime=getscantime(d.scan,d.data);
    xv=plsinfo('xval',d.scan.data.pulsegroups(1).name,[],scantime);
    xv = xv(1,:);
    %make an educated case where the center is
    [val ind]=max(diff(data));
    center=xv(ind);
    inds=xv>(center-width) & xv<(center+width);
    xv=xv(inds);
    data=data(inds);
    xv=flipud(xv);
    data=flipud(data);

    fitfn=@(p,x) p(1) +p(2).*x + p(3)./(exp(((x-p(4))./p(5)))+1)+p(6).*x.^2; %fermi
    %fitfn=@(p,x) p(1) +p(2).*x -p(3).*tanh((x-p(4))./p(5))+p(6).*x.^2; %tanh


    mask = [1 1 1 1 1 1]; 
    beta0=[data(1) (data(2)-data(1))./(xv(2)-xv(1)) amp center .1 0];
    [beta,~,~,~,~,err] = fitwrap('plinit plfit',xv,data,beta0,fitfn, mask);
    fit=fitfn(beta,xv);
    figure(5);
    subplot(7,6,i); hold on; plot(xv,data,'k.'); plot(xv,fit,'b');
    title(sprintf('Width is %.0f ueV\nLever arm is %.2f',beta(5)*1000,beta(2)));
    widthFit(i)=beta(5);
    widthErr(i)=err(1,5,1);
    
end

tempFit=widthFit.*max(MCtemp*1000)./max(widthFit)
tempFitErr=widthErr.*max(MCtemp*1000)./max(widthFit)
figure(2); clf; errorbar(MCtemp*1000,tempFit,tempFitErr,'bo');
xlabel('MC temp (mK)'); ylabel('Temperature (mK)');
ax=axis;
axis([0 ax(2) 0 ax(4)]);
hold on;
[val ind]=max(widthFit);
plot([0 MCtemp(ind)]*1000,[0 tempFit(ind)],'r')

%% replot against electron temp
Ttherm=190; %assume electrons are thermalized above this temperature
inds=MCtemp.*1000>Ttherm;
fitfn=@(p,x) p(1).*x; %fit temperatures above this to a line going through zero
beta0=widthFit(5)/MCtemp(5);
beta=fitwrap('plinit plfit',MCtemp(inds),widthFit(inds),beta0,fitfn);
figure(3); clf; plot(MCtemp*1000,widthFit*1e3./beta(1),'bo'); 

fit=fitfn(beta,MCtemp);
hold on; plot(MCtemp*1000,fit*1e3./beta(1),'r')
xlabel('MC Temperature (mK)');
ylabel('Temperature (MK)');
